version: "3"
services:
  # nginx    #########################################################
  nginx:
    image: p6-nginx:${DOCKER_TAG_NGINX}
    restart: always
    tty: true
    ports:
      - "80:80"

  # frontend #########################################################
  front-dev:
    image: p6-front:${DOCKER_TAG_FRONTEND}
    restart: always
    tty: true
    volumes:
      - "./app/frontend/p6-front:/root/p6-front"
    ports:
      - "3000:3000"
    working_dir: /root/p6-front
    depends_on:
      - nginx

  front-prod:
    image: p6-front:${DOCKER_TAG_FRONTEND}
    restart: always
    ports:
      - "3000:3000"
    working_dir: /root/p6-front
    depends_on:
      - nginx
    command: npm run start
